use medical_diagnosis_db;

INSERT INTO diseases (disease_name, description) VALUES
('Fungal infection', 'Infection caused by fungi affecting skin, nails, or lungs.'),
('Allergy', 'Immune system reaction to foreign substances like pollen or food.'),
('GERD', 'Chronic acid reflux causing irritation in the esophagus.'),
('Chronic cholestasis', 'Long-term reduction or stoppage of bile flow from the liver.'),
('Drug Reaction', 'Adverse response of the body to a medication.'),
('Peptic ulcer disease', 'Sores that develop on the stomach lining or small intestine.'),
('AIDS', 'Advanced stage of HIV infection damaging the immune system.'),
('Diabetes', 'Condition causing high blood sugar due to insulin issues.'),
('Gastroenteritis', 'Inflammation of stomach and intestines causing diarrhea and vomiting.'),
('Bronchial Asthma', 'Chronic condition causing airway inflammation and breathing difficulty.'),
('Hypertension', 'High blood pressure increasing risk of heart disease.'),
('Migraine', 'Severe headache often accompanied by nausea and sensitivity to light.'),
('Cervical spondylosis', 'Age-related wear affecting spinal discs in the neck.'),
('Paralysis (brain hemorrhage)', 'Loss of muscle function due to brain bleeding.'),
('Jaundice', 'Yellowing of skin and eyes due to liver dysfunction.'),
('Malaria', 'Mosquito-borne disease caused by Plasmodium parasites.'),
('Chicken pox', 'Viral infection causing itchy skin rash and blisters.'),
('Dengue', 'Mosquito-borne viral infection causing high fever and joint pain.'),
('Typhoid', 'Bacterial infection spread through contaminated food and water.'),
('Hepatitis A', 'Liver infection caused by hepatitis A virus, usually from contaminated food.'),
('Hepatitis B', 'Serious liver infection transmitted through blood or body fluids.'),
('Hepatitis C', 'Chronic liver infection spread mainly through infected blood.'),
('Hepatitis D', 'Severe liver infection that occurs only with hepatitis B.'),
('Hepatitis E', 'Waterborne liver infection common in developing regions.'),
('Alcoholic hepatitis', 'Liver inflammation caused by excessive alcohol consumption.'),
('Tuberculosis', 'Bacterial infection mainly affecting lungs.'),
('Common Cold', 'Viral infection of the upper respiratory tract.'),
('Pneumonia', 'Infection causing inflammation in the air sacs of lungs.'),
('Dimorphic hemorrhoids (piles)', 'Swollen veins in the rectum or anus causing discomfort.'),
('Heart attack', 'Blockage of blood flow to the heart muscle.'),
('Varicose veins', 'Enlarged twisted veins usually in legs due to poor circulation.'),
('Hypothyroidism', 'Underactive thyroid causing slow metabolism.'),
('Hyperthyroidism', 'Overactive thyroid causing rapid metabolism.'),
('Hypoglycemia', 'Abnormally low blood sugar levels.'),
('Osteoarthritis', 'Degenerative joint disease causing cartilage breakdown.'),
('Arthritis', 'Inflammation of joints causing pain and stiffness.'),
('(vertigo) Paroxysmal Positional Vertigo', 'Sudden dizziness caused by inner ear problems.'),
('Acne', 'Skin condition causing pimples due to clogged pores.'),
('Urinary tract infection', 'Infection in urinary system, often bladder or urethra.'),
('Psoriasis', 'Autoimmune skin condition causing red, scaly patches.'),
('Impetigo', 'Contagious bacterial skin infection common in children.');

select * from symptoms
order by symptom_id asc;